### ISSUE TITLE
Visibilidad de las restricciones

### ISSUE THREAD

**Issue by DZSanhueza** [ciudadanointeligente/abre#100]
Al momento de enviar una propuesta, las restricciones no están visibles. De hecho, no es tan fácil encontrarlas en la página. Podrían aparecer en la ventana para crear la propuesta para que el vecino las tenga en cuenta.

**Comment by daquiroz** [comment]
Por ahora se agregó un campo de Resumen de las restricciones, para que esten más a mano. Falta que la municipalidad complete este campo

**Comment by daquiroz** [comment]
En la iteración 2 de la plataforma se hará también #109
