### ISSUE TITLE
Términos y condiciones al verificar la cuenta

### ISSUE THREAD

**Issue by daquiroz** [ciudadanointeligente/abre#113]
Cuando una persona se verifica, se le pedirá rut, fecha de nacimiento, dirección y unidad vecinal. En este mismo formulario debe aceptar unos términos. Agregó unas primeras líneas de lo que pienso deben tener, feedback y cambios son recibidos.

> Para verificar la cuenta hay que tener X años o más, y ser de la comuna de Peñalolen. Aceptando el proceso de verificación acepta dar su consentimiento para que funcionarios de la Municipalidad revisen la información proporcionada y la contraresten con la de las bases de datos del Municipio de Peñalolen.

**Comment by Bastiantorres** [comment]
Para verificar _su cuenta debe tener_ X años o más, y ser de la comuna de Peñalolen. Aceptando el proceso de verificación, _da_ su consentimiento para que funcionarios de la Municipalidad revisen la información proporcionada y la contraresten con la de las bases de datos del Municipio de Peñalolen _para comprobar la veracidad de la misma_.

**Comment by daquiroz** [comment]
Queda así:

> Para verificar su cuenta debe ser de la comuna de Peñalolen. Aceptando el proceso de verificación, da su consentimiento para que funcionarios de la Municipalidad revisen la información proporcionada y la contraresten con la de las bases de datos del Municipio de Peñalolen para comprobar la veracidad de la misma.
