### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by daquiroz** [ciudadanointeligente/abre#24]
- [x] Darle más importancia a la invitación a hacer propuestas
- [x] Mostrar una foto del parque
- [x] Agregar un link después de los gif

**Comment by manuelbarrosr** [comment]
- [ ] Arreglar disposición menú superior (palabra "Peñalolén" queda rara)
- [x] Mostrar "desafío activo"
- [x] Hacer (?) todo el home más fluido e intuitivo
