### ISSUE TITLE
En resumen de la propuesta: sale problem en inglés y me asigna un territorio que no marqué

### ISSUE THREAD

**Issue by margamaira** [ciudadanointeligente/abre#64]
Cuando envié la propuesta y me muestra el resumen, arriba dice Problem Title. 
Y me aparece un tag abajo indicando que es una propuesta para toda la comuna, siendo que no marqué eso en ningún momento. Además, al hacer clic en ese tag me lleva a una page donde dice que no hay propuestas de ese territorio arriba :S

**Comment by daquiroz** [comment]
La comunidad afectada, cuando se crea una propuesta para un desafío, es la misma que tiene el desafío, entonces no se le pregunta a la persona. ¿Crees que es necesario explicitarlo por ahí?

Notar que esta actualizada la vista de una propuesta:
https://abre.penalolen.cl/proposals/4-a-relajarse-un-poco-vecinos
