### ISSUE TITLE
Problemas con el registro por facebook

### ISSUE THREAD

**Issue by cyanez95** [ciudadanointeligente/abre#83]
![image](https://user-images.githubusercontent.com/30244541/28288459-3e32f3d0-6b0d-11e7-8bbb-44cbaad32a16.png)

No sé si es porque mi nombre de usuario no está disponible, o es un problema aparte.

**Comment by jbci** [comment]
creo el problema en este caso es q tu cuenta de fb no tiene un email asociado, es asi?

**Comment by cyanez95** [comment]
Siii tienes razón, pensé que tenía asociado un email a fb pero no es así

**Comment by daquiroz** [comment]
Voy a cambiar el mensaje para que les quede claro a las personas que les pase eso, que puede ser por un nombre de usuario ya utilizado o por no tener el mail asociado, indicandoles que se registren usando un mail
